# FFT Spec
dft_win     = 256
dft_step    = 128
ceps_filter = 32

# VAT
vat_moving     = 15
vat_percentile = 0.85
vat_min_len    = 50

# ALIGN AND CLUSTERING
warping_band_percentage = 0.15
insertion_penalty       = 1.0
deletion_penalty        = 1.0
match_penalty           = 0.5
alignment_workers       = 8 
clustering_percentile   = 0.1

# MODEL MERGING 
merging_percentile          = 0.45
merging_internal_percentile = 0.95
merging_moving              = 15