# FFT Spec
dft_win       = 256                  # DFT window
dft_step      = 128                  # How many samples to skip
ceps_filter   = 32                   # triangular filters of cepstrum
auto_encoder  = 15   		     # auto encoder dim
learning_rate = 0.001		     # auto encoder lr
epochs        = 25                   # epochs

# VAT
vat_moving     = 15                # moving average of variance / frame
vat_percentile = 0.95              # 95% of observations in the audio are noise
vat_min_len    = 150               # minimum length of a signal is 50 frames
               
# ALIGN AND CLUSTERING             
warping_band_percentage = 0.1       # sakoe shiba band
insertion_penalty       = 1.0       # [0:1] Weight distance at on insertion path
deletion_penalty        = 1.0       # [0:1] Weight distance at on deletion path
match_penalty           = 1.0       # [0:1] Weight distance at on matching path
alignment_workers       = 4         # 8 threads / worker
clustering_percentile   = 0.05      # 5% of alignments can be merged
