img_w       = "20pt"
img_h       = "24pt"
out_docs    = "output/docs"
out_images  = "output/img" 
out_audio   = "output/audio"  
document    = "project/templates/document.tex"
dendogram   = "project/templates/dendogram.tex"
figure      = "project/templates/figure.tex"
table       = "project/templates/table.tex"
result_html = "project/templates/result_page.html"